import type { Achievement, AchievementId } from '@/types/achievement';

export const ACHIEVEMENTS: Record<AchievementId, Achievement> = {
  // First Steps
  first_habit: {
    id: 'first_habit',
    name: 'First Steps',
    description: 'Create your first habit',
    icon: 'rocket',
    color: '#FFD700',
    category: 'habits',
    requirement: { type: 'habits', value: 1 },
    isPremium: false,
    rarity: 'common',
  },
  first_checkin: {
    id: 'first_checkin',
    name: 'Getting Started',
    description: 'Complete your first check-in',
    icon: 'checkmark-circle',
    color: '#00FF00',
    category: 'completion',
    requirement: { type: 'completions', value: 1 },
    isPremium: false,
    rarity: 'common',
  },

  // Streaks
  streak_7: {
    id: 'streak_7',
    name: 'Week Warrior',
    description: 'Maintain a 7-day streak',
    icon: 'flame',
    color: '#FF6B35',
    category: 'streaks',
    requirement: { type: 'streak', value: 7 },
    isPremium: false,
    rarity: 'common',
  },
  streak_14: {
    id: 'streak_14',
    name: 'Two Week Titan',
    description: 'Maintain a 14-day streak',
    icon: 'flame',
    color: '#FF6B35',
    category: 'streaks',
    requirement: { type: 'streak', value: 14 },
    isPremium: false,
    rarity: 'common',
  },
  streak_30: {
    id: 'streak_30',
    name: 'Monthly Master',
    description: 'Maintain a 30-day streak',
    icon: 'flame',
    color: '#FF6B35',
    category: 'streaks',
    requirement: { type: 'streak', value: 30 },
    isPremium: false,
    rarity: 'rare',
  },
  streak_60: {
    id: 'streak_60',
    name: 'Dedication Champion',
    description: 'Maintain a 60-day streak',
    icon: 'flame',
    color: '#FF1493',
    category: 'streaks',
    requirement: { type: 'streak', value: 60 },
    isPremium: false,
    rarity: 'rare',
  },
  streak_90: {
    id: 'streak_90',
    name: 'Quarter King',
    description: 'Maintain a 90-day streak',
    icon: 'flame',
    color: '#FF1493',
    category: 'streaks',
    requirement: { type: 'streak', value: 90 },
    isPremium: false,
    rarity: 'epic',
  },
  streak_180: {
    id: 'streak_180',
    name: 'Half Year Hero',
    description: 'Maintain a 180-day streak',
    icon: 'flame',
    color: '#9D00FF',
    category: 'streaks',
    requirement: { type: 'streak', value: 180 },
    isPremium: false,
    rarity: 'epic',
  },
  streak_365: {
    id: 'streak_365',
    name: 'Year Long Legend',
    description: 'Maintain a 365-day streak',
    icon: 'trophy',
    color: '#FFD700',
    category: 'streaks',
    requirement: { type: 'streak', value: 365 },
    isPremium: false,
    rarity: 'legendary',
  },

  // Completions
  completions_10: {
    id: 'completions_10',
    name: 'Perfect 10',
    description: 'Complete 10 total check-ins',
    icon: 'checkbox',
    color: '#00FFFF',
    category: 'completion',
    requirement: { type: 'completions', value: 10 },
    isPremium: false,
    rarity: 'common',
  },
  completions_50: {
    id: 'completions_50',
    name: 'Half Century',
    description: 'Complete 50 total check-ins',
    icon: 'checkbox',
    color: '#00FFFF',
    category: 'completion',
    requirement: { type: 'completions', value: 50 },
    isPremium: false,
    rarity: 'common',
  },
  completions_100: {
    id: 'completions_100',
    name: 'Century Club',
    description: 'Complete 100 total check-ins',
    icon: 'checkbox',
    color: '#00FFFF',
    category: 'completion',
    requirement: { type: 'completions', value: 100 },
    isPremium: false,
    rarity: 'rare',
  },
  completions_500: {
    id: 'completions_500',
    name: 'Consistency Master',
    description: 'Complete 500 total check-ins',
    icon: 'checkbox',
    color: '#FF69B4',
    category: 'completion',
    requirement: { type: 'completions', value: 500 },
    isPremium: false,
    rarity: 'epic',
  },
  completions_1000: {
    id: 'completions_1000',
    name: 'Thousand Strong',
    description: 'Complete 1000 total check-ins',
    icon: 'trophy',
    color: '#FFD700',
    category: 'completion',
    requirement: { type: 'completions', value: 1000 },
    isPremium: false,
    rarity: 'legendary',
  },

  // Habits
  habits_5: {
    id: 'habits_5',
    name: 'Habit Collector',
    description: 'Create 5 habits',
    icon: 'list',
    color: '#00FF00',
    category: 'habits',
    requirement: { type: 'habits', value: 5 },
    isPremium: false,
    rarity: 'common',
  },
  habits_10: {
    id: 'habits_10',
    name: 'Routine Builder',
    description: 'Create 10 habits',
    icon: 'list',
    color: '#00FF00',
    category: 'habits',
    requirement: { type: 'habits', value: 10 },
    isPremium: false,
    rarity: 'rare',
  },
  habits_20: {
    id: 'habits_20',
    name: 'Lifestyle Architect',
    description: 'Create 20 habits',
    icon: 'list',
    color: '#9D00FF',
    category: 'habits',
    requirement: { type: 'habits', value: 20 },
    isPremium: false,
    rarity: 'epic',
  },

  // Perfect Performance
  perfect_week: {
    id: 'perfect_week',
    name: 'Perfect Week',
    description: 'Complete all habits for 7 consecutive days',
    icon: 'star',
    color: '#FFD700',
    category: 'streaks',
    requirement: { type: 'special', condition: 'perfect_week' },
    isPremium: false,
    rarity: 'rare',
  },
  perfect_month: {
    id: 'perfect_month',
    name: 'Flawless Month',
    description: 'Complete all habits for 30 consecutive days',
    icon: 'star',
    color: '#FFD700',
    category: 'streaks',
    requirement: { type: 'special', condition: 'perfect_month' },
    isPremium: false,
    rarity: 'legendary',
  },

  // Timing
  early_bird_7: {
    id: 'early_bird_7',
    name: 'Early Bird',
    description: 'Check in before 8 AM for 7 consecutive days',
    icon: 'sunny',
    color: '#FFD700',
    category: 'timing',
    requirement: { type: 'timing', condition: 'before_8am_7days' },
    isPremium: false,
    rarity: 'rare',
  },
  night_owl_7: {
    id: 'night_owl_7',
    name: 'Night Owl',
    description: 'Check in after 8 PM for 7 consecutive days',
    icon: 'moon',
    color: '#9D00FF',
    category: 'timing',
    requirement: { type: 'timing', condition: 'after_8pm_7days' },
    isPremium: false,
    rarity: 'rare',
  },

  // Special
  comeback_kid: {
    id: 'comeback_kid',
    name: 'Comeback Kid',
    description: 'Start a new streak after breaking one',
    icon: 'refresh',
    color: '#00FFFF',
    category: 'special',
    requirement: { type: 'special', condition: 'restart_after_break' },
    isPremium: false,
    rarity: 'common',
  },
  consistency_king: {
    id: 'consistency_king',
    name: 'Consistency King',
    description: 'Maintain 90% completion rate for 30 days',
    icon: 'ribbon',
    color: '#FF69B4',
    category: 'special',
    requirement: { type: 'special', condition: '90_percent_30days' },
    isPremium: false,
    rarity: 'epic',
  },

  // Premium Exclusive
  premium_member: {
    id: 'premium_member',
    name: 'Premium Member',
    description: 'Join the Premium club',
    icon: 'diamond',
    color: '#FFD700',
    category: 'premium',
    requirement: { type: 'premium' },
    isPremium: true,
    rarity: 'epic',
  },
  theme_master: {
    id: 'theme_master',
    name: 'Theme Master',
    description: 'Try 3 different premium themes',
    icon: 'color-palette',
    color: '#FF69B4',
    category: 'premium',
    requirement: { type: 'premium', condition: '3_themes' },
    isPremium: true,
    rarity: 'rare',
  },
  note_taker: {
    id: 'note_taker',
    name: 'Reflective Soul',
    description: 'Add notes to 10 check-ins',
    icon: 'document-text',
    color: '#00FFFF',
    category: 'premium',
    requirement: { type: 'premium', condition: '10_notes' },
    isPremium: true,
    rarity: 'rare',
  },
};

export const getAllAchievements = (): Achievement[] => {
  return Object.values(ACHIEVEMENTS);
};

export const getAchievementsByCategory = (category: string): Achievement[] => {
  return Object.values(ACHIEVEMENTS).filter((a) => a.category === category);
};

export const getAchievementById = (id: AchievementId): Achievement | undefined => {
  return ACHIEVEMENTS[id];
};
